# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20170427_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('answers', models.ManyToManyField(to='courses.Answer')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.Call')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.Course')),
                ('questions', models.ManyToManyField(to='courses.Question')),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
    ]
